config/routes.rb
Rails.application.routes.draw do
  # devise routes
  devise_for :lawyers
  devise_for :clients, controllers: { sessions: 'clients/sessions' }
  as :client do
    get 'login', to: 'clients/sessions#new'
  end

  # site routes
  root to: 'application#main'
  get 'pedido', to: 'application#order'
  post 'order', to: 'application#create'
  get 'pedido/sucesso', to: 'application#success'

  # app routes
  namespace :app do
    root to: 'orders#index'
    resources :orders, only: [:index, :show, :new, :create], path: 'pedidos'
    get 'meu_advogado', to: 'lawyers#show', as: :lawyer
  end

  namespace :adv do
    root to: 'orders#index'
    resources :orders, only: [:index, :show, :update], path: 'pedidos'
    resources :clients, only: [:index, :show], path: '/clients' do
      resources :orders, only: [:index], path: 'pedidos'
    end
    resources :matches, only: [:index, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  belongs_to :lawyer, optional: true, counter_cache: true
  has_many :orders, dependent: :restrict_with_error
  has_many :matches, dependent: :restrict_with_error
  accepts_nested_attributes_for :orders

  validates :name, :city, :state, :name, :phone, presence: true
end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :clients, dependent: :restrict_with_error
  has_many :orders, through: :clients
  has_many :matches, dependent: :restrict_with_error

  validates :cpf, :city, :state, :phone, :name, presence: true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :client
  belongs_to :lawyer

  validates :situation, presence: true

  enum situation: { awaiting_approval: 0, refused: 1, accepted: 2 }

  after_update :connect_client_to_lawyer, if: proc { accepted? }

  private

  def connect_client_to_lawyer
    client.lawyer = lawyer
    client.save!
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client
  has_one :lawyer, through: :client

  enum problem_type: { flight: 0, baggage: 1 }
  enum status: { pending: 0, under_review: 1, success: 2, failed: 3, canceled: 4 }

  validates :description, :date, presence: true

  after_create :generate_match, if: proc { client.orders.count == 1 }

  private

  def generate_match
    lawyer = Lawyer.where(state: client.state).order(clients_count: :asc).first
    lawyer = Lawyer.order(clients_count: :asc).first if lawyer.nil?
    Match.create(
      client: client,
      lawyer: lawyer,
      situation: 'awaiting_approval'
    )
  end
end

app/controllers/adv/clients_controller.rb
class Adv::ClientsController < AdvController
  def index
    @clients = current_lawyer.clients
  end
end

app/controllers/adv/matches_controller.rb
class Adv::MatchesController < AdvController
  def index
    @matches = current_lawyer.matches.awaiting_approval
  end

  def update
    @match = Match.find(params[:id])
    respond_to do |format|
      if @match.update(situation: params[:situation])
        format.html { redirect_to adv_matches_path, notice: 'Match atualizado com sucesso' }
      else
        format.html { render :index, notice: @match.errors.full_messages }
      end
    end
  end
end

app/controllers/adv/orders_controller.rb
class Adv::OrdersController < AdvController
  def index
    @orders =
      if params[:client_id] && Client.find(params[:client_id]).lawyer == current_lawyer
        Client.find(params[:client_id]).orders
      else
        current_lawyer.orders.order(updated_at: :desc)
      end
  end

  def show
    @order = Order.find(params[:id])
    @client = @order.client
  end

  def update
    @order = Order.find(params[:id])
    respond_to do |format|
      if @order.update(status: params[:status])
        format.html { redirect_to adv_orders_path, notice: 'Pedido atualizado com sucesso' }
      else
        format.html { render :index, notice: @order.errors.full_messages }
      end
    end
  end
end

app/controllers/adv_controller.rb
class AdvController < ApplicationController
  layout 'adv'
  before_action :authenticate_lawyer!
end

app/controllers/app/lawyers_controller.rb
class App::LawyersController < AppController
  def show
    @lawyer = current_client.lawyer
  end
end

app/controllers/app/orders_controller.rb
class App::OrdersController < AppController
  before_action :check_lawyer, only: [:new, :create]

  def index
    @orders = current_client.orders.order(updated_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @lawyer = @order.lawyer
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.client = current_client
    respond_to do |format|
      if @order.save!
        format.html { redirect_to app_orders_path, notice: 'Pedido feito com sucesso' }
      else
        format.html { render :new, notice: @order.errors.full_messages }
      end
    end
  end

  private

  def check_lawyer
    redirect_to app_orders_path if current_client.lawyer.nil?
  end

  def order_params
    params.require(:order).permit(:date, :description, :problem_type)
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  layout 'app'
  before_action :authenticate_client!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def main
  end

  def order
    @client = Client.new
    @client.orders.build
  end

  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save!
        format.html { redirect_to pedido_sucesso_path }
      else
        format.html { render :order, notice: @client.errors.full_messages }
      end
    end
  end

  def success
  end

  private

  def client_params
    params.require(:client).permit(:name, :email, :phone, :city, :state, :password,
      orders_attributes: [:problem_type, :description, :date])
  end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

class Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/app/orders_helper.rb
module App::OrdersHelper
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adv/clients/index.html.erb
<div class="row justify-content-around">
  <% @clients.each do |client| %>
    <div class="col-xs-12 col-sm-12 col-md-6">
      <div class="card">
        <div class="card-header">
          Cliente: <%= client.name %>
        </div>
        <div class="card-body">
          <div class="media">
            <img src="https://i.pravatar.cc/100" class="mr-3" alt="Advogado">
            <div class="media-body">
              <h5 class="mt-0"><%= "#{client.city}, #{client.state}"%></h5>
              <a href="https://wa.me/<%= client.phone.gsub(/[^0-9]/, '') %>"><i class="icon ion-logo-whatsapp"></i></a>
              <a href="mailto:<%= client.email %>"><i class="icon ion-md-mail"></i></a> <br>
              <%= link_to 'Ver pedidos', adv_client_orders_path(client), class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/adv/matches/index.html.erb
<div class="row">
  <% @matches.each do |match|%>
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-xs-12 col-sm-8">
              <div class="media">
                <img src="https://i.pravatar.cc/100" class="mr-3" alt="Advogado">
                <div class="media-body">
                  <h5 class="mt-0"><%= match.client.name %></h5>
                  <h6 class="mt-0"><%= "#{match.client.city}, #{match.client.state}"%></h6>
                  <a href="https://wa.me/<%= match.client.phone.gsub(/[^0-9]/, '') %>"><i class="icon ion-logo-whatsapp"></i></a>
                  <a href="mailto:<%= match.client.email %>"><i class="icon ion-md-mail"></i></a> <br>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4 text-right">
              <%= button_to 'Aceitar', adv_match_path(match), method: :patch, params: { situation: 'accepted' }, class: 'btn btn-success' %>
              <%= button_to 'Recusar', adv_match_path(match), method: :patch, params: { situation: 'refused' }, class: 'btn btn-danger' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/adv/orders/index.html.erb
<div class="row justify-content-around">
  <% @orders.each do |order| %>
    <div class="col-xs-12 col-sm-12 col-md-5 m-1 align-self-center">
      <%= render partial: 'shared/order', object: order, locals: { show: false } %>
    </div>
  <% end %>
</div>

app/views/adv/orders/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6">
    <%= render partial: 'shared/order', object: @order, locals: { show: true } %>
  </div>
  <% if @client %>
    <div class="col-xs-12 col-sm-12 col-md-6">
      <div class="card">
        <div class="card-header">
          Cliente: <%= @client.name %>
        </div>
        <div class="card-body">
          <div class="media">
            <img src="https://i.pravatar.cc/100" class="mr-3" alt="Advogado">
            <div class="media-body">
              <h5 class="mt-0"><%= "#{@client.city}, #{@client.state}"%></h5>
              <a href="https://wa.me/<%= @client.phone.gsub(/[^0-9]/, '') %>"><i class="icon ion-logo-whatsapp"></i></a>
              <a href="mailto:<%= @client.email %>"><i class="icon ion-md-mail"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/app/lawyers/show.html.erb
<h3 class="text-center">Perfil do meu advogado</h3>
<div class="row h-100 align-items-center justify-content-center">
  <div class="col-xs-12 col-sm-8 col-md-5">
    <div class="card">
      <div class="card-header">
        Advogado: <%= @lawyer.name %>
      </div>
      <div class="card-body">
        <div class="media">
          <img src="https://i.pravatar.cc/100" class="mr-3" alt="Advogado">
          <div class="media-body">
            <h5 class="mt-0"><%= "#{@lawyer.city}, #{@lawyer.state}"%></h5>
            <h6>CPF: <%= @lawyer.cpf %></h6>
            <a href="https://wa.me/<%= @lawyer.phone.gsub(/[^0-9]/, '') %>"><i class="icon ion-logo-whatsapp"></i></a>
            <a href="mailto:<%= @lawyer.email %>"><i class="icon ion-md-mail"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/app/orders/index.html.erb
<% if current_client.lawyer %>
  <div class="row mb-5">
    <div class="col text-center">
      <%= link_to 'Novo pedido', new_app_order_path, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<div class="row justify-content-around">
  <% @orders.each do |order| %>
    <div class="col-xs-12 col-sm-12 col-md-5 m-1 align-self-center">
      <%= render partial: '/shared/order', object: order, locals: { show: false } %>
    </div>
  <% end %>
</div>

app/views/app/orders/new.html.erb
<div class="row h-100 align-items-cente">
  <div class="col">
    <div class="card">
      <%= form_for [:app, @order] do |f| %>
        <div class="card-header">
          Cadastro de Pedido
        </div>
        <div class="card-body">
          <h4 class="text-center">Descrição do pedido</h4>
          <div class="form-group">
            <%= f.label :date %>
            <%= f.date_field :date %>
          </div>
          <div class="form-group">
            <%= f.label :problem_type %>
            <%= f.collection_radio_buttons :problem_type, Order.problem_types_i18n, :first, :second do |r| %>
              <div class="form-check">
                <%= r.radio_button(class: 'form-check-input') %>
                <%= r.label(class: 'form-check-label') %>
              </div>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <%= f.submit 'Enviar', class: 'btn btn-primary btn-block' %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/app/orders/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6">
    <%= render partial: 'shared/order', object: @order, locals: { show: true } %>
  </div>
  <% if @lawyer %>
    <div class="col-xs-12 col-sm-12 col-md-6">
      <div class="card">
        <div class="card-header">
          Advogado: <%= @lawyer.name %>
        </div>
        <div class="card-body">
          <div class="media">
            <img src="https://i.pravatar.cc/100" class="mr-3" alt="Advogado">
            <div class="media-body">
              <h5 class="mt-0"><%= "#{@lawyer.city}, #{@lawyer.state}"%></h5>
              <h6>CPF: <%= @lawyer.cpf %></h6>
              <a href="https://wa.me/<%= @lawyer.phone.gsub(/[^0-9]/, '') %>"><i class="icon ion-logo-whatsapp"></i></a>
              <a href="mailto:<%= @lawyer.email %>"><i class="icon ion-md-mail"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/application/main.html.erb
<div class="main">
  <div class="bg"></div>
  <div class="skin"></div>
  <div class="content">
    <h1>Problemas com seu voo?</h1>
    <h2>Com a gente seu problema é Resolvvido ;)</h2>
    <div class="row w-50">
      <div class="col-6">
        <%= link_to 'Fazer pedido', pedido_path, class: 'btn btn-info btn-block' %>
      </div>
      <div class="col-6">
        <%= link_to 'Entrar', app_root_path, class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
</div>

app/views/application/order.html.erb
<div class="order">
  <div class="container h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <div class="card mt-5">
          <div class="card-body">
            <h3 class="text-center">
              Resolvvido
            </h3>
            <h6 class="text-center">Realizar pedido</h6>
            <hr>
            <%= form_with model: @client, url: order_path, method: :post, local: true do |f|%>
              <h4 class="text-center">Informações Pessoais</h4>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :phone %>
                <%= f.text_field :phone, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :city %>
                <%= f.text_field :city, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :state %>
                <%= f.text_field :state, class: 'form-control' %>
              </div>
              <hr>
              <%= f.fields_for :orders do |ff| %>
                <h4 class="text-center">Descrição do pedido</h4>
                <div class="form-group">
                  <%= ff.label :date %>
                  <%= ff.date_field :date %>
                </div>
                <div class="form-group">
                  <%= ff.label :problem_type %>
                  <%= ff.collection_radio_buttons :problem_type, Order.problem_types_i18n, :first, :second do |r| %>
                    <div class="form-check">
                      <%= r.radio_button(class: 'form-check-input') %>
                      <%= r.label(class: 'form-check-label') %>
                    </div>
                  <% end %>
                </div>
                <div class="form-group">
                  <%= ff.label :description %>
                  <%= ff.text_area :description, class: 'form-control' %>
                </div>
              <% end %>
              <%= f.submit 'Enviar', class: 'btn btn-primary btn-block'%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/success.html.erb
<div class="container h-100">
  <div class="row h-100 align-items-center">
    <div class="col">
      <div class="jumbotron">
        <h1 class="display-4">PARABÉNS :)!</h1>
        <p class="lead">Seu pedido foi efetuado com sucesso e agora estrou em análise para um de nossos advogados.</p>
        <hr class="my-4">
        <p>Para mais informações, faça o login abaixo.</p>
        <%= link_to 'login', login_path, class: 'btn btn-block btn-lg btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/adv.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Resolvvido</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- controller styles -->
    <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track': 'reload' if (::Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.scss") && params[:controller] != 'application' %>

    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet" data-turbolinks-track="reload">
  </head>

  <body>
    <!-- header start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Resolvvido</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Pedidos', adv_orders_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Clientes', adv_clients_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Matches', adv_matches_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sair', destroy_lawyer_session_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <!-- header end -->

    <!-- content start -->
    <div class="container mt-5">
      <%= yield %>
    </div>
    <!-- content end -->
  </body>
</html>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Resolvvido</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- controller styles -->
    <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track': 'reload' if (::Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.scss") && params[:controller] != 'application' %>

    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet" data-turbolinks-track="reload">
  </head>

  <body>
    <!-- header start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Resolvvido</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Pedidos', app_orders_path, class: 'nav-link' %>
          </li>
          <% if current_client.lawyer %>
            <li class="nav-item active">
              <%= link_to 'Meu Advogado', app_lawyer_path, class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Sair', destroy_client_session_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <!-- header end -->

    <!-- content start -->
    <div class="container mt-5">
      <%= yield %>
    </div>
    <!-- content end -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Resolvvido</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- controller styles -->
    <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track': 'reload' if (::Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.scss") && params[:controller] != 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_order.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-6 text-left">
        <%= order.date.strftime("%d/%m/%Y") %>
      </div>
      <div class="col-6 text-right">
        <% if order.flight? %>
          Voo <i class="icon ion-md-airplane"></i>
        <% else %>
          Bagagem <i class="icon ion-md-briefcase"></i>
        <% end %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-12">
        <% if order.pending? %>
          <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading">Pendente</h4>
            <p>O pedido ainda não foi visto pelo advogado.</p>
          </div>
        <% elsif order.under_review? %>
          <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">Em análise</h4>
            <p>Pedido está sendo analisado por uma advogado.</p>
          </div>
        <% elsif order.success? %>
          <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Sucesso!</h4>
            <p>Conseguimos concluir o processo e a indenização foi concedida. :D</p>
          </div>
        <% elsif order.failed? %>
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Falha</h4>
            <p>Infelizmente não foi possível conseguir a indenização :(</p>
          </div>
        <% elsif order.canceled? %>
          <div class="alert alert-dark" role="alert">
            <h4 class="alert-heading">Cancelado</h4>
            <p>O pedido foi cancelado.</p>
          </div>
        <% end %>
      </div>
    </div>
    <% if show %>
      <h6>Descrição</h6>
      <p> <%= order.description %> </p>
    <% else %>
      <% if current_client.nil? %>
        <%= link_to 'Mais Informações', adv_order_path(order), class: 'btn btn-primary' %>
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Atualizar
          </button>
          <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <%= button_to 'Pendente', adv_order_path(order), method: :patch, params: { status: 'pending' }, class: 'dropdown-item' %>
            <%= button_to 'Em análise', adv_order_path(order), method: :patch, params: { status: 'under_review' }, class: 'dropdown-item' %>
            <%= button_to 'Sucesso', adv_order_path(order), method: :patch, params: { status: 'success' }, class: 'dropdown-item' %>
            <%= button_to 'Falha', adv_order_path(order), method: :patch, params: { status: 'failed' }, class: 'dropdown-item' %>
            <%= button_to 'Cancelado', adv_order_path(order), method: :patch, params: { status: 'canceled' }, class: 'dropdown-item' %>
          </div>
        </div>
      <% else %>
        <%= link_to 'Mais Informações', app_order_path(order), class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    Última atualização há <%= time_ago_in_words(order.updated_at) %>
  </div>
</div>